export const listDisputes = async () => {}
export const showDisputeDetails = async () => {}
export const acceptDispute = async () => {}
export const appealDispute = async () => {}
export const settleDispute = async () => {}
export const updateDisputeDetails = async () => {}
export const makeOfferToResolveDispute = async () => {}
export const provideEvidance = async () => {}
export const acknowledgeReturnItem = async () => {}
export const provideSupportingInformationForDispute = async () => {}
export const esclateDisputeToClaim = async () => {}
export const acceptOfferToResolveDispute = async () => {}
export const sendMessageAboutDisputeToOtherParty = async () => {}
export const denyOfferToResolveDispute = async () => {}
export const partiallyUpdateDisputeDetails = async () => {}
