export async function generateInvoiceNumber() {}
export async function createDraftInvoice() {}
export async function showInvoiceDetails() {}
export async function listInvoices() {}
export async function generateQRCode() {}
export async function updateInvoice() {}
export async function sendInvoice() {}
export async function sendInvoiceRemainder() {}
export async function cancelInvoice() {}
export async function deleteInvoice() {}
export async function searchInvoices() {}
export async function recordPaymentInvoices() {}
export async function deletePayment() {}
export async function recordRefundInvoice() {}
export async function deleteRefundInvoice() {}
